# Generated by Django 5.1.3 on 2024-12-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtpPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('name_first', models.TextField(blank=True, null=True)),
                ('name_last', models.TextField(blank=True, null=True)),
                ('hand', models.TextField(blank=True, null=True)),
                ('dob', models.IntegerField(blank=True, null=True)),
                ('ioc', models.TextField(blank=True, null=True)),
                ('height', models.TextField(blank=True, null=True)),
                ('wikidata_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atp_players',
                'managed': False,
            },
        ),
    ]
