# Generated by Django 5.1.3 on 2024-12-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_player'),
        ('players', '0002_atpplayers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
