# Generated by Django 5.1.3 on 2024-12-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_atpmatches2023_atpmatches2024_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atpmatches2024',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='atpplayers',
            options={'managed': False},
        ),
    ]
